### ISSUE TITLE
How to find the best hyperparameters in finetuning with wandb

### ISSUE THREAD

**Issue by XuperX** [XuperX/useful_snippets#4]
1.  configure wandb running parameters
```yaml
program: run_ner.py
method: bayesian  # for example
metric:
  name: val_accuracy
  goal: maximize
parameters:
  learning_rate:
    min: 0.001
    max: 0.1
  epochs:
    values: [10, 20, 30]
  batch_size:
    values: [16, 32, 64]
```
2.. initialise the Sweep on wandb

```sh
WB_KEY=$(cat ~/TOKEN/WB_token)
wandb login $WB_KEY

# sweep provides output as stderr. making things a bit complicated
wandb sweep sweep.yaml > temp 2>&1
# cat temp
# Somehow awk do not work
# agent_loc contains the sweep id
cat temp | grep "Run sweep agent with: "|rev | cut -d' ' -f1 | rev > agent_loc
SWP=$(cat agent_loc)
wandb agent $SWP
```
